### ISSUE TITLE
Closedxml error after merging cells

### ISSUE THREAD

**Issue by 208047758** [ClosedXML/ClosedXML#197]
Can anyone assist, I am generating an excel document using C#. I use ClosedXML v0.86.0 to format the document prior saving it into a directory.

The problem is that when I open the document I get an error: We found a problem with some content in xxxx.xlsx. Do you want us to try recover as much as we can? When I click yes the document open up but I get the following:

Removed Feature: Table from /xl/tables/table.xml part (Table)
Removed Feature: Table from /xl/tables/table2.xml part (Table)

I tried troubleshooting the problem and it only happens if there merged cells in the spreadsheet.

Does anyone know how to avoid this issue?

**Comment by vbjay** [comment]
https://closedxml.codeplex.com/workitem/9360. Submitted this issue years
ago.

**Comment by igitur** [comment]
@vbjay I can't replicate your issue on Codeplex using the files that you attached there. I suspect this is a different cause.

@208047758 Please paste your code for how you generate your files.

**Comment by vbjay** [comment]
I figured it was resolved but the message looks the same. I figured the
cause may be the same. I know in my case I had set up a template. Loaded
the template using closed XML and adjusted the size of the table based on
the data coming in and filled the table from a linq query. Then I would
save. It would start the tables at 2 instead of 1 as the error and
resolution report mention. Figured that bug would direct you to where you
need to look.

**Comment by igitur** [comment]
@208047758 Please try ClosedXML v0.87 (released on 2017-04-02). If you still experience the problem, let us know and we'll reopen the issue.

**Comment by ganesh3010** [comment]
still getting this error.

My code is:
var cellCount = ws.Range(oDtToExport.Rows.Count - 1, 2, oDtToExport.Rows.Count, 2);
							cellCount.Style.Alignment.SetVertical(XLAlignmentVerticalValues.Center);
							cellCount.Merge();

							var cellPercent = ws.Range(oDtToExport.Rows.Count + 1, 2, oDtToExport.Rows.Count + 2, 2);
							cellPercent.Style.Alignment.SetVertical(XLAlignmentVerticalValues.Center);
							cellPercent.Merge();

**Comment by igitur** [comment]
@ganesh3010 Please open a new issue and complete the issue template fully.

**Comment by Nashiki-Bowser** [comment]
> https://closedxml.codeplex.com/workitem/9360. Submitted this issue years ago.
> […](#)

Your link isn’t working, can you please explain, I have the same problem now.
