### ISSUE TITLE
0.104.1 FormulaParser ParsingException in XLTable.ReplaceData

### ISSUE THREAD

**Issue by RemcoBlok** [ClosedXML/ClosedXML#2425]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.104.1

**What is the current behavior?**

I have an IXLTable with a single row. One field contains a formula based on the other fields. When I call `ReplaceData()` on the table passing in an array of business objects T with more than one item, such that the IXLTable needs to insert rows, I get the following exception in 0.104.1. 

```
ClosedXML.Parser.ParsingException: Error at char 0 of '': Unexpected token EofSymbolId.
   at ClosedXML.Parser.FormulaParser`3.RefAtomExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefSpillExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefRangeExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefIntersectionExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefImplicitExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.AtomExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.PrefixAtomExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.PercentExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.PowExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.MultiplyingExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.AdditiveExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.ConcatExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.Expression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.Formula()
   at ClosedXML.Parser.FormulaParser`3.CellFormulaA1(String formula, TContext context, IAstFactory`3 factory)
   at ClosedXML.Excel.CalcEngine.Visitors.FormulaReferences.ForFormula(String formula) in /_/ClosedXML/Excel/CalcEngine/Visitors/FormulaReferences.cs:line 41
   at ClosedXML.Excel.XLDefinedName.set_RefersTo(String value) in /_/ClosedXML/Excel/DefinedNames/XLDefinedName.cs:line 74
   at ClosedXML.Excel.XLDefinedName.SetRefersTo(String formula) in /_/ClosedXML/Excel/DefinedNames/XLDefinedName.cs:line 140
   at ClosedXML.Excel.XLWorksheet.MoveDefinedNamesRows(XLRange range, Int32 rowsShifted, XLDefinedNames definedNames) in /_/ClosedXML/Excel/XLWorksheet.cs:line 1474
   at ClosedXML.Excel.XLWorksheet.WorksheetRangeShiftedRows(XLRange range, Int32 rowsShifted) in /_/ClosedXML/Excel/XLWorksheet.cs:line 1337
   at ClosedXML.Excel.XLWorksheet.NotifyRangeShiftedRows(XLRange range, Int32 rowsShifted) in /_/ClosedXML/Excel/XLWorksheet.cs:line 1496
   at ClosedXML.Excel.XLRangeBase.InsertRowsAboveInternal(Boolean onlyUsedCells, Int32 numberOfRows, Boolean formatFromAbove, Boolean nullReturn) in /_/ClosedXML/Excel/Ranges/XLRangeBase.cs:line 1297
   at ClosedXML.Excel.XLRangeBase.InsertRowsBelowInternal(Boolean onlyUsedCells, Int32 numberOfRows, Boolean formatFromAbove, Boolean nullReturn) in /_/ClosedXML/Excel/Ranges/XLRangeBase.cs:line 1215
   at ClosedXML.Excel.XLRangeBase.InsertRowsBelow(Boolean onlyUsedCells, Int32 numberOfRows, Boolean formatFromAbove) in /_/ClosedXML/Excel/Ranges/XLRangeBase.cs:line 1192
   at ClosedXML.Excel.XLRangeBase.InsertRowsBelow(Int32 numberOfRows, Boolean expandRange) in /_/ClosedXML/Excel/Ranges/XLRangeBase.cs:line 1171
   at ClosedXML.Excel.XLHelper.InsertRowsWithoutEvents(Func`3 insertFunc, XLTableRange tableRange, Int32 numberOfRows, Boolean expandTable) in /_/ClosedXML/XLHelper.cs:line 245
   at ClosedXML.Excel.XLTableRow.InsertRowsBelow(Int32 numberOfRows) in /_/ClosedXML/Excel/Tables/XLTableRow.cs:line 109
   at ClosedXML.Excel.XLTable.ReplaceData[T](IEnumerable`1 data, Boolean propagateExtraColumns) in /_/ClosedXML/Excel/Tables/XLTable.cs:line 985
```

The same exception occurs when the IXLTable initially has multiple rows and calling  `ReplaceData()` passing in an array of business objects containing fewer items such that the IXLTable needs to delete rows.

```
ClosedXML.Parser.ParsingException: Error at char 0 of '': Unexpected token EofSymbolId.
   at ClosedXML.Parser.FormulaParser`3.RefAtomExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefSpillExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefRangeExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefIntersectionExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefImplicitExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.RefExpression(Boolean replaceFirstAtom, TNode refAtom)
   at ClosedXML.Parser.FormulaParser`3.AtomExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.PrefixAtomExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.PercentExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.PowExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.MultiplyingExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.AdditiveExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.ConcatExpression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.Expression(Boolean skipRangeUnion, Boolean& isPureRef)
   at ClosedXML.Parser.FormulaParser`3.Formula()
   at ClosedXML.Parser.FormulaParser`3.CellFormulaA1(String formula, TContext context, IAstFactory`3 factory)
   at ClosedXML.Excel.CalcEngine.Visitors.FormulaReferences.ForFormula(String formula) in /_/ClosedXML/Excel/CalcEngine/Visitors/FormulaReferences.cs:line 41
   at ClosedXML.Excel.XLDefinedName.set_RefersTo(String value) in /_/ClosedXML/Excel/DefinedNames/XLDefinedName.cs:line 74
   at ClosedXML.Excel.XLDefinedName.SetRefersTo(String formula) in /_/ClosedXML/Excel/DefinedNames/XLDefinedName.cs:line 140
   at ClosedXML.Excel.XLWorksheet.MoveDefinedNamesRows(XLRange range, Int32 rowsShifted, XLDefinedNames definedNames) in /_/ClosedXML/Excel/XLWorksheet.cs:line 1474
   at ClosedXML.Excel.XLWorksheet.WorksheetRangeShiftedRows(XLRange range, Int32 rowsShifted) in /_/ClosedXML/Excel/XLWorksheet.cs:line 1337
   at ClosedXML.Excel.XLWorksheet.NotifyRangeShiftedRows(XLRange range, Int32 rowsShifted) in /_/ClosedXML/Excel/XLWorksheet.cs:line 1496
   at ClosedXML.Excel.XLRangeBase.Delete(XLShiftDeletedCells shiftDeleteCells) in /_/ClosedXML/Excel/Ranges/XLRangeBase.cs:line 1428
   at ClosedXML.Excel.XLTableRow.Delete() in /_/ClosedXML/Excel/Tables/XLTableRow.cs:line 114
   at ClosedXML.Excel.XLTableRows.<>c.<Delete>b__7_1(XLTableRow r) in /_/ClosedXML/Excel/Tables/XLTableRows.cs:line 51
   at ClosedXML.Excel.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in /_/ClosedXML/Extensions/EnumerableExtensions.cs:line 14
   at ClosedXML.Excel.XLTableRows.Delete() in /_/ClosedXML/Excel/Tables/XLTableRows.cs:line 51
   at ClosedXML.Excel.XLTable.ReplaceData[T](IEnumerable`1 data, Boolean propagateExtraColumns) in /_/ClosedXML/Excel/Tables/XLTable.cs:line 988
```

I don't think the cell formula itself matters as this exception is a regression. It worked fine in 0.104.0-preview2. But for completeness, the cell formula is `=TIME(0,[@Time],0)` where Time is another field in the table containing minutes as a number.

Excel automatically creates a defined range for the entire table data range. In addition I also created a defined range for each individual field's column of data. These defined ranges are expected to automatically expand or contract as `ReplaceData()` inserts or deletes rows.

See the attached sample spreadsheet.

**What is the expected behavior or new feature?**

The `ReplaceData()` method should not throw an exception and correctly replace the data, inserting or deleting rows accordingly, including cells with formula.

**Is this a regression from the previous version?**

This worked fine in 0.104.0-preview2. I did not use the previous stable version 0.102.3 as that had a bug incorrectly determining a cell's DataType as a DateTime instead of TimeSpan. 0.104.0-preview2 did not have this bug. For this reason I used 0.104.0-preview2 for about 6 months.

## Reproducibility

Use the attached sample spreadsheet and run the code below.

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

class Program
{
    static void Main()
    {
        string path = "Data\\Test.xlsx";

        using (IXLWorkbook workBook = new XLWorkbook(path))
        {
            string name = "Normal";

            Item[] data = new Item[]
            {
                new Item { Time = 0, Power = 0 },
                new Item { Time = 1, Power = 0 }
            };

            IXLWorksheet worksheet = workBook.Worksheet(name);

            IXLTable table = worksheet.Table(name);

            table.ReplaceData(data, propagateExtraColumns: true);
        }
    }
}

class Item
{
    public decimal Time
    { get; set; }

    public decimal Power
    { get; set; }
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Test.xlsx](https://github.com/user-attachments/files/17226654/Test.xlsx)

**Comment by dusk0r** [comment]
I have the same exception when loading an existing spreadsheet. Reverted to 0.102.3 and it works again.

**Comment by patrickklaeren** [comment]
Confirming same issue as above. Works As dusk0r mentioned, reverting to .102.3 works.

**Comment by ramioh** [comment]
@RemcoBlok, Your attached file has invalid names. Go to `Formulas` -> `Name Manager`, and delete the broken ones. Doing the same thing fixed it for me.

**Comment by hevilhuy** [comment]
@Igor-Zlatomrezhev  Will commit your changes to the official main branch? Your branch fixed the problem for me.

**Comment by abiddle-lcs** [comment]
I'm having a similar issue but with  DataRange.InsertRowsBelow(). Removing the invalid names didn't fix it for me
[FINAL CLRK 2024 BudgetTesting.xlsx](https://github.com/user-attachments/files/17509308/FINAL.CLRK.2024.BudgetTesting.xlsx)

**Comment by KulikovEkb** [comment]
Same exception for `worksheet.Row(<n>).InsertRowsBelow(<n>)`

**Comment by Domivan** [comment]
Same exception for v 0.104.2 worksheet.Row(<n>).InsertRowsAbove(<n>)

**Comment by wismag** [comment]
Same exception for v0.104.1 and v0.104.2 for worksheet.Row(cell.Address.RowNumber).Delete()

**Comment by RemcoBlok** [comment]
> @RemcoBlok, Your attached file has invalid names. Go to `Formulas` -> `Name Manager`, and delete the broken ones. Doing the same thing fixed it for me.

Deleting the invalid names did not fix the issue for me.

**Comment by RemcoBlok** [comment]
@jahav are you able to merge PR #2462 from @Igor-Zlatomrezhev?

**Comment by jahav** [comment]
Fixed in #2462.

Whole shifting of components in reaction to structural changes is half-WIP ATM in land of regressions (even standard shifting doesn't work properly, much less non-reference name formula`1 + Sheet!$A$1`). The PR at least stops exceptions.

**Comment by RemcoBlok** [comment]
@jahav  Super! Thank you!

**Comment by cleerax** [comment]
Still getting this exception on 0.105.0 for `worksheet.Column(<n>).InsertColumnsBefore(<n>)`. Reverting to 0.104.0-preview2 works.

I'm not entirely sure, but it seems that https://github.com/ClosedXML/ClosedXML/pull/2462 made changes only considering moving rows, not columns

**Comment by cleerax** [comment]
https://github.com/ClosedXML/ClosedXML/pull/2462
