### ISSUE TITLE
Duplicate id attribute in NonVisualDrawingProperties

### ISSUE THREAD

**Issue by nathanQiu1** [ClosedXML/ClosedXML#769]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

branch : CFConsolidate

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#

   public void Main()
{
      using (XLWorkbook workbook = new XLWorkbook(@"FAI.xlsm"))
   {
       workbook.Save();
   }

}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[test7.xlsx](https://github.com/ClosedXML/ClosedXML/files/1886929/test7.xlsx)
[test8.xlsx](https://github.com/ClosedXML/ClosedXML/files/1886930/test8.xlsx)

**Comment by nathanQiu1** [comment]
@Pankraty  0.91.0  no problem，Check box text 'overlap'

**Comment by Pankraty** [comment]
Thanks. Will look at it.

**Comment by nathanQiu1** [comment]
Thank you @igitur , actually 0.91.0 is good, but it will make the template change color, this problem is for the branch: CFConsolidate. Because this branch can basically not change color, but there are many problems, for version 0.91.0 can, this branch can not.

**Comment by igitur** [comment]
Different problems are solved in different pull requests. You'll have to wait for the pull requests to be merged and released, or build your own version of ClosedXML by merging the branches that you want.

Do you confirm that #770 fixes the exception that you reported in this issue?

**Comment by nathanQiu1** [comment]
Thank you for your reminder, I'm not sure if these problems are caused by the side effects of modifying the conditional format, perhaps after the merger of the branch code still exists.
  #770 may not completely solve the problem of template changing color, but it greatly reduces the possibility of changing the color.

**Comment by igitur** [comment]
No, this issue is totally unrelated to conditional formatting.

**Comment by igitur** [comment]
Keep this issue open. It wil automatically be closed when the fix is merged.

**Comment by nathanQiu1** [comment]
Sorry, it may not be resolved.
[checkbox.xlsx](https://github.com/ClosedXML/ClosedXML/files/1903015/checkbox.xlsx)

**Comment by igitur** [comment]
This issue is closed. Please open a new one.
