### ISSUE TITLE
ClosedXML throwing an exception when deployed to aws lambda

### ISSUE THREAD

**Issue by Yeshwant-Numino** [ClosedXML/ClosedXML#970]
- [x] Bug

**Version of ClosedXML**
 v 0.93.0

**Current Behavior**
I have an AWS lambda that reads data from an excel file. I have used ClosedXml v 0.93.0 with .net core 2.
The function works as expected when running on localhost but gives an error:
> {"error":"The type initializer for 'ClosedXML.Excel.XLHelper' threw an exception."}

when deployed on AWS lambda.

**Exception StackTrace**

> at ClosedXML.Excel.XLWorksheet.Ranges(String ranges)\n
> at ClosedXML.Excel.XLWorkbook.LoadSheetViews(SheetViews sheetViews, XLWorksheet ws)\n
> at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)\n
> at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)\n

I have done some research and found that ClosedXml, DocumentFormat.OpenExcel, ExcelNumberFormat, and FastMember do not work with one another when deployed to another machine and running within a service application.

[stackoverflow link](https://stackoverflow.com/questions/49658881/closedxml-documentformat-openexcel-excelnumberformat-and-fastmember)

Also there have been instances of failure to load dll's on AWS Lambda(Linux machines).

So i'm not sure what is causing the issue as the function works as expected when running on localhost

**Did this work in previous versions of our tool?  Which versions?**

No, I have tested it with versions: 0.93.1 and 0.92.1.

## Reproducibility
**Create a function to read an excel file and publish it on AWS Lambda**

**Code to reproduce problem:**
using (XLWorkbook workBook = new XLWorkbook(excelData))//->This line throws the exception
          
I have also tested the file that I post to the method, there are no issues in it.

Any help will be appreciated.

**Comment by vbjay** [comment]
https://aws.amazon.com/lambda/

https://aws.amazon.com/athena/

**Comment by Thierry-S** [comment]
Having a quick look at the code... the problem seems to be that the XLHelper class (which is a collection of utility methods) has a static Graphic instance used for getting DPI (for font size calculations)… In my case, I doubt that we actually need that code so it’s a shame it’s not isolated. Even if it were anyway, it would still leave a runtime bug waiting to happen if we stumbled into part of the API that needed it. 

I’m a bit ignorant of how this works but could we compile libgdiplus and distribute it with the lambda function code?
We are using other libraries in Lambda and we have so far not seen this type of problems. I wonder what we can do as a work around, or what can be done to ClosedXML to make it work when deployed there?

**Comment by vbjay** [comment]
My point is I don't think closedxml is a good fit for what you are doing.
AWS already has ways to read excel spreadsheet data.
https://docs.aws.amazon.com/quicksight/latest/user/create-a-data-set-excel.html

**Comment by Thierry-S** [comment]
Thanks for the reply @vbjay . However, due to various reasons, I have to use closedXML, so switching to something else is not an option for me, therefore discussing whether it's a good fit doesn't help me.
I'm more after a technical solution.

Going from https://stackoverflow.com/questions/50615704/unable-to-load-dll-libdl-when-using-system-drawing-common-nuget-package-on-aws
Ended up on https://github.com/dotnet/corefx/issues/25102
Or even https://github.com/VahidN/EPPlus.Core/issues/41 with a gdiplus issue on EPPlus, not surprisingly another Excel library, with a similar exception: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module or one of its dependencies could not be found.
And ending up here: https://github.com/dotnet/corefx/issues/17135 with a specific post on gdiplus: https://github.com/dotnet/corefx/issues/17135#issuecomment-353632964 and its own issue here: https://github.com/JanKallman/EPPlus/issues/83

We'll try some of these and report back, but if anyone has other suggestions, let us know! Thanks.

**Comment by ThomsCass** [comment]
I've the same thing on azure function... Is there a solution ?
`ClosedXML: The type initializer for 'ClosedXML.Excel.XLHelper' threw an exception. System.Drawing.Common: System.Drawing is not supported on this platform.`

**Comment by nefcanto** [comment]
I have the same error here in Windows 10:

`The type initializer for 'ClosedXML.Excel.XLHelper' threw an exception.

   at ClosedXML.Excel.XLHelper.ValidateName(String objectType, String newName, String oldName, IEnumerable`1 existingNames, String& message)
   at ClosedXML.Excel.XLTable.set_Name(String value)
   at ClosedXML.Excel.XLWorksheet.Table(XLRange range, String name, Boolean addToTables, Boolean setAutofilter)
   at ClosedXML.Excel.XLRange.CreateTable()
   at ClosedXML.Excel.XLCell.InsertTable[T](IEnumerable`1 data, String tableName, Boolean createTable)
   at ClosedXML.Excel.XLCell.InsertTable(DataTable data, String tableName, Boolean createTable)
   at ClosedXML.Excel.XLWorksheets.Add(DataTable dataTable, String sheetName)

System.Drawing is not supported on this platform.

   at ClosedXML.Excel.XLHelper..cctor()`

**Comment by igitur** [comment]
@nefcanto That should be fixed (or at least improved) in #1025

**Comment by igitur** [comment]
For other `System.Drawing` issues on AWS and Azure, see https://stackoverflow.com/a/51907024/179494

**Comment by nefcanto** [comment]
@igitur based on your guidance I upgraded to the latest version, that is `0.93.1` and I still get the same error. I'm not running on UWP or AWS or Azure Functions. I'm simply running my ASP.NET Core app on Windows 10.

**Comment by igitur** [comment]
@nefcanto #1025 is targeted for the 0.94 release.
